server:
  servlet:
    context-path: /api
    session:
      timeout: 20m
  port: ${PORT:8080}

spring:
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/EASY_LEARN
    driverClassName: org.postgresql.Driver
    hikari:
      schema: easy_learn
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    protocol: smtp
  batch:
    job:
      enabled: false
    initialize-schema: always

logging:
  level:
    com.easylearn: debug
    org.hibernate.SQL: debug